name: ui-e2e-test
on:
  push:
    branches:
      - "main"
      - "develop"
      - "next"
      - "test-selenium-pipeline"
jobs:
  run-ui-e2e-tests:
    name: Run UI e2e tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install selenium
        run: pip install selenium

      - name: run tests
        working-directory: ui_tests
        run: |
          python second.py